[build]
buildCommand = "chmod +x mvnw && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/projetoEletro-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
